/**
 * Sprint 2C PR-C4 — Owner /store/photos rich mock fixture.
 *
 * Reference: `docs/design/reference/store-photos.jsx` (12 photos).
 * 18장으로 확장 (베타 시연 첫인상). MOCK_FIXTURES=true 단독 의존.
 *
 * 데이터 적재 후 신규 DAL(photo_analyses 테이블 예정)로 swap. 스키마 변경
 * 시점은 Epic B AI Photo Analysis 정식 도입 PR.
 */

export type PhotoStatus = "booked" | "review" | "failed";

export interface MockPhoto {
  readonly id: number;
  readonly customer: string;
  readonly flag: string;
  readonly country: string;
  readonly stylist: string | null;
  readonly stylistInitial: string | null;
  readonly score: number;
  readonly status: PhotoStatus;
  readonly height: number;
  readonly when: string;
  readonly thickness: number | null;
  readonly technique: string | null;
  readonly portfolio: number;
  readonly tags: ReadonlyArray<string>;
  readonly notes: string;
  readonly vip?: boolean;
}

export const STYLIST_COLORS: Readonly<Record<string, string>> = {
  민: "#E8A97A",
  현: "#7AB6A1",
  유: "#9B8AC4",
  소: "#E8A0B0",
};

export const mockPhotos: ReadonlyArray<MockPhoto> = [
  {
    id: 1,
    customer: "사쿠라",
    flag: "🇯🇵",
    country: "Tokyo, Japan",
    stylist: "민지",
    stylistInitial: "민",
    score: 94,
    status: "booked",
    height: 280,
    when: "12분 전",
    thickness: 0.52,
    technique: "포인트컷 + 슬라이드",
    portfolio: 7,
    tags: ["미디엄레이어드", "내추럴웨이브"],
    notes: "둥근 얼굴형 → 옆머리로 윤곽 보정",
  },
  {
    id: 2,
    customer: "Linh Pham",
    flag: "🇻🇳",
    country: "Hanoi, Vietnam",
    stylist: "현주",
    stylistInitial: "현",
    score: 89,
    status: "review",
    height: 240,
    when: "23분 전",
    thickness: 0.61,
    technique: "발레아쥬 + 톤다운",
    portfolio: 4,
    tags: ["허니브라운", "그라데이션"],
    notes: "검은 모발 → 자연스러운 명도 차이 추천",
  },
  {
    id: 3,
    customer: "Wei Chen",
    flag: "🇨🇳",
    country: "Beijing, China",
    stylist: null,
    stylistInitial: null,
    score: 41,
    status: "failed",
    height: 220,
    when: "1시간 전",
    thickness: null,
    technique: null,
    portfolio: 0,
    tags: ["요청 모호"],
    notes: "참고 사진 + 텍스트 요청 일치도 낮음",
  },
  {
    id: 4,
    customer: "Emma Park",
    flag: "🇺🇸",
    country: "NYC, USA",
    stylist: "민지",
    stylistInitial: "민",
    score: 96,
    status: "booked",
    height: 320,
    when: "1시간 전",
    thickness: 0.48,
    technique: "C컬펌 + 트리트먼트",
    portfolio: 12,
    tags: ["S컬", "내추럴"],
    notes: "브라이덜 — 10월 결혼식 대비",
  },
  {
    id: 5,
    customer: "Yuki Tanaka",
    flag: "🇯🇵",
    country: "Osaka, Japan",
    stylist: "유진",
    stylistInitial: "유",
    score: 82,
    status: "booked",
    height: 260,
    when: "2시간 전",
    thickness: 0.55,
    technique: "단발 + 사이드뱅",
    portfolio: 5,
    tags: ["턱선단발"],
    notes: "직모 — 볼륨 매직 권장",
  },
  {
    id: 6,
    customer: "박서윤",
    flag: "🇰🇷",
    country: "Seoul, Korea",
    stylist: "소연",
    stylistInitial: "소",
    score: 91,
    status: "review",
    height: 230,
    when: "3시간 전",
    thickness: 0.58,
    technique: "롱레이어드",
    portfolio: 9,
    tags: ["긴머리", "S컬"],
    notes: "현재 길이 유지 + 결만 정리",
  },
  {
    id: 7,
    customer: "Mei Zhang",
    flag: "🇨🇳",
    country: "Shanghai, China",
    stylist: "민지",
    stylistInitial: "민",
    score: 78,
    status: "review",
    height: 270,
    when: "5시간 전",
    thickness: 0.5,
    technique: "프리미엄 케어",
    portfolio: 3,
    tags: ["트리트먼트"],
    notes: "탈색 손상모 → 케어 우선",
  },
  {
    id: 8,
    customer: "Camille D.",
    flag: "🇫🇷",
    country: "Paris, France",
    stylist: null,
    stylistInitial: null,
    score: 38,
    status: "failed",
    height: 210,
    when: "6시간 전",
    thickness: null,
    technique: null,
    portfolio: 0,
    tags: ["사진 품질 낮음"],
    notes: "조명 부족 — 재촬영 요청 발송됨",
  },
  {
    id: 9,
    customer: "정유나",
    flag: "🇰🇷",
    country: "Gangnam, Seoul",
    stylist: "현주",
    stylistInitial: "현",
    score: 95,
    status: "booked",
    height: 290,
    when: "어제",
    thickness: 0.62,
    technique: "컬러 보정 + 컷",
    portfolio: 11,
    tags: ["애쉬브라운"],
    notes: "VIP — 5년 단골",
    vip: true,
  },
  {
    id: 10,
    customer: "Aiko N.",
    flag: "🇯🇵",
    country: "Tokyo, Japan",
    stylist: "유진",
    stylistInitial: "유",
    score: 86,
    status: "booked",
    height: 250,
    when: "어제",
    thickness: 0.53,
    technique: "C컬 매직",
    portfolio: 6,
    tags: ["볼륨매직"],
    notes: "C컬 + 시스루뱅",
  },
  {
    id: 11,
    customer: "Hana Kim",
    flag: "🇺🇸",
    country: "LA, USA",
    stylist: "소연",
    stylistInitial: "소",
    score: 84,
    status: "review",
    height: 220,
    when: "어제",
    thickness: 0.57,
    technique: "옴브레",
    portfolio: 5,
    tags: ["옴브레"],
    notes: "끝부분만 톤다운 — 손상 최소화",
  },
  {
    id: 12,
    customer: "Ana Silva",
    flag: "🇧🇷",
    country: "São Paulo, Brazil",
    stylist: "민지",
    stylistInitial: "민",
    score: 79,
    status: "review",
    height: 270,
    when: "어제",
    thickness: 0.54,
    technique: "발레아쥬",
    portfolio: 4,
    tags: ["발레아쥬", "내추럴"],
    notes: "어두운 모발 → 굵은 하이라이트",
  },
  {
    id: 13,
    customer: "Sophia Lee",
    flag: "🇸🇬",
    country: "Singapore",
    stylist: "현주",
    stylistInitial: "현",
    score: 88,
    status: "booked",
    height: 240,
    when: "2일 전",
    thickness: 0.56,
    technique: "매직 스트레이트",
    portfolio: 8,
    tags: ["스트레이트"],
    notes: "곱슬 + 두꺼운 모발 → 풀스트레이트 권장",
    vip: true,
  },
  {
    id: 14,
    customer: "Maya R.",
    flag: "🇹🇭",
    country: "Bangkok, Thailand",
    stylist: "유진",
    stylistInitial: "유",
    score: 81,
    status: "review",
    height: 200,
    when: "2일 전",
    thickness: 0.5,
    technique: "레이어드 컷",
    portfolio: 6,
    tags: ["레이어드"],
    notes: "얼굴형 보정 컷 추천",
  },
  {
    id: 15,
    customer: "이지은",
    flag: "🇰🇷",
    country: "Hongdae, Seoul",
    stylist: "소연",
    stylistInitial: "소",
    score: 92,
    status: "booked",
    height: 280,
    when: "2일 전",
    thickness: 0.59,
    technique: "허쉬 컷",
    portfolio: 10,
    tags: ["허쉬", "S컬"],
    notes: "유행 컷 — 자연스러운 결",
  },
  {
    id: 16,
    customer: "Yui M.",
    flag: "🇯🇵",
    country: "Kyoto, Japan",
    stylist: "민지",
    stylistInitial: "민",
    score: 87,
    status: "booked",
    height: 220,
    when: "3일 전",
    thickness: 0.51,
    technique: "C컬펌",
    portfolio: 9,
    tags: ["C컬", "여리여리"],
    notes: "자연스러운 컬 + 끝매직",
  },
  {
    id: 17,
    customer: "Olivia W.",
    flag: "🇬🇧",
    country: "London, UK",
    stylist: null,
    stylistInitial: null,
    score: 45,
    status: "failed",
    height: 210,
    when: "3일 전",
    thickness: null,
    technique: null,
    portfolio: 0,
    tags: ["참고 사진 불명"],
    notes: "이미지 해상도 너무 낮음 — 재촬영 안내",
  },
  {
    id: 18,
    customer: "최예린",
    flag: "🇰🇷",
    country: "Busan, Korea",
    stylist: "현주",
    stylistInitial: "현",
    score: 93,
    status: "booked",
    height: 290,
    when: "3일 전",
    thickness: 0.6,
    technique: "롱헤어 트리트먼트",
    portfolio: 12,
    tags: ["롱헤어", "케어"],
    notes: "VIP — 3년 단골, 트리트먼트만",
    vip: true,
  },
];

export const mockPhotoStats = {
  weekTotal: 142,
  weekMatched: 124,
  weekMatchRate: 87,
  avgConfidence: 82,
  failedCount: 18,
  vipCount: 12,
};
